{% set name = "mplfinance" %}
{% set version = "0.12.10b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7da150b5851aa5119ad6e06b55e48338b619bb6773f1b85df5de67a5ffd917bf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - pandas
    - python >=3.6

test:
  imports:
    - mplfinance
    - mplfinance._styledata

about:
  home: http://github.com/matplotlib/mplfinance
  license: LicenseRef-PSF-based
  license_url: https://github.com/matplotlib/mplfinance/blob/master/LICENSE
  license_family: PSF
  license_file: LICENSE
  summary: Utilities for the visualization, and visual analysis, of financial data
  doc_url: https://github.com/matplotlib/mplfinance#contents-and-tutorials
  dev_url: http://github.com/matplotlib/mplfinance

extra:
  recipe-maintainers:
    - DanielGoldfarb
